language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"
install: 
    - "python setup.py install"
    - "pip install coveralls --use-mirrors"
script: "coverage run --source=dyndnsc setup.py test"
after_success: "coveralls"
matrix:
    allow_failures:
        python: pypy
